# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.vm.network "public_network",
        use_dhcp_assigned_default_route: true
    config.vm.network "forwarded_port", guest: 4001, host: 4001
    config.vm.network "forwarded_port", guest: 5001, host: 5001
end
